export const UNIQUE_CODE_LENGTH = 8;
export const UNIQUE_CODE_MIN_LENGTH = 4;
export const UNIQUE_CODE_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
export const UNIQUE_CODE_ATTEMPTS = 8;
export const UNIQUE_INSERT_ATTEMPTS = 3;
